### ISSUE TITLE
Potential Bug in demo.py

### ISSUE THREAD

**Issue by Mingyuan1997** [2y7c3/Super-Resolution-Neural-Operator#1]
Thanks for your contribution! There might be a small dimension bug in the demo.py. Could you help me out?

python demo.py --input input.jpg --model save/rdn_epoch-1000.pth --scale 2 --output output.png
torch.Size([3, 135, 240])
Traceback (most recent call last):
  File "/superresolution/Super-Resolution-Neural-Operator/demo.py", line 42, in <module>
    pred = model(((img - 0.5) / 0.5).cuda().unsqueeze(0),coord.unsqueeze(0), cell_factor*cell.unsqueeze(0))
  File "/anaconda3/envs/sr5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/superresolution/Super-Resolution-Neural-Operator/models/sronet.py", line 103, in forward
    return self.query_rgb(coord, cell)
  File "/superresolution/Super-Resolution-Neural-Operator/models/sronet.py", line 77, in query_rgb
    rel_cell[:,1] *= feat.shape[-1]
IndexError: index 1 is out of bounds for dimension 1 with size 1

**Comment by 2y7c3** [comment]
The bug has been fixed, thank you for your attention.
